import "./globals.css";

export const metadata = {
  title: "SaavnPlyr",
  description: "Generated by SaavnPlyr",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=" bg">
      <body className="">{children}</body>
    </html>
  );
}
